name: CI - Guardrails & Eval

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install eval deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-eval.txt

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch OPENAI_API_KEY from Key Vault
        run: |
          echo "OPENAI_API_KEY=$(az keyvault secret show --vault-name kv-rag-12345 --name OpenAIKey --query value -o tsv)" >> $GITHUB_ENV

      - name: Run Ragas eval
        env:
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        run: |
          python eval_ragas.py

      - name: Run Promptfoo eval
        env:
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        run: |
          npx -y promptfoo@latest eval -c promptfooconfig.yaml --no-cache --max-concurrency 1
